'use strict';

// Used to pre-populate the JSData store with some known categories
// Use `npm run fetch-categories` to retrieve and updated list

angular.module('reallyGoodEmailsApp')
  .constant('categories', [
    {"id": 232, "count": 21, "name": "Abandoned Cart", "slug": "abandoned-cart"},
    {"id": 282, "count": 9, "name": "Account", "slug": "account"},
    {"id": 447, "count": 9, "name": "Activation", "slug": "activation"},
    {"id": 211, "count": 3, "name": "Activity", "slug": "activity"},
    {"id": 44, "count": 41, "name": "Alerts", "slug": "alerts"},
    {"id": 102, "count": 130, "name": "Announcement", "slug": "announcement"},
    {"id": 668, "count": 1, "name": "Apology", "slug": "apology"},
    {"id": 301, "count": 472, "name": "App", "slug": "app"},
    {"id": 437, "count": 1, "name": "Authentication", "slug": "authentication"},
    {"id": 265, "count": 12, "name": "Automated", "slug": "automated"},
    {"id": 874, "count": 6, "name": "B2B", "slug": "b2b"},
    {"id": 706, "count": 1, "name": "Checkout", "slug": "checkout"},
    {"id": 247, "count": 10, "name": "Comments", "slug": "comments"},
    {"id": 166, "count": 60, "name": "Confirmation", "slug": "confirmation"},
    {"id": 390, "count": 12, "name": "Copy", "slug": "copy"},
    {"id": 292, "count": 11, "name": "Coupon", "slug": "coupon"},
    {"id": 385, "count": 21, "name": "Curated", "slug": "curated"},
    {"id": 181, "count": 21, "name": "Customer Appreciation", "slug": "customer-appreciation"},
    {"id": 642, "count": 4, "name": "Customer Happiness", "slug": "customer-happiness"},
    {"id": 480, "count": 3, "name": "Customer Service", "slug": "customer-service"},
    {"id": 183, "count": 4, "name": "Deactivation", "slug": "deactivation"},
    {"id": 779, "count": 5, "name": "Discount", "slug": "discount"},
    {"id": 216, "count": 34, "name": "Discovery", "slug": "discovery"},
    {"id": 475, "count": 16, "name": "Download", "slug": "download"},
    {"id": 151, "count": 563, "name": "Ecommerce", "slug": "ecommerce"},
    {"id": 284, "count": 11, "name": "Education", "slug": "education"},
    {"id": 106, "count": 176, "name": "Email Digest", "slug": "email-digest"},
    {"id": 175, "count": 22, "name": "Engagement", "slug": "engagement"},
    {"id": 145, "count": 38, "name": "Events", "slug": "events"},
    {"id": 199, "count": 2, "name": "Expiration", "slug": "expiration"},
    {"id": 4, "count": 75, "name": "Featured Product", "slug": "featured-product"},
    {"id": 280, "count": 2, "name": "Feed", "slug": "feed"},
    {"id": 308, "count": 93, "name": "GIF", "slug": "gif"},
    {"id": 348, "count": 11, "name": "Giveaway", "slug": "giveaway"},
    {"id": 271, "count": 72, "name": "Holiday", "slug": "holiday"},
    {"id": 772, "count": 6, "name": "Informational", "slug": "informational"},
    {"id": 872, "count": 1, "name": "Interactive", "slug": "interactive"},
    {"id": 163, "count": 40, "name": "Invitation", "slug": "invitation"},
    {"id": 604, "count": 1, "name": "Layout", "slug": "layout"},
    {"id": 417, "count": 7, "name": "Legal", "slug": "legal"},
    {"id": 585, "count": 15, "name": "Longform", "slug": "longform"},
    {"id": 226, "count": 32, "name": "Marketing", "slug": "marketing"},
    {"id": 314, "count": 11, "name": "Marketplace", "slug": "marketplace"},
    {"id": 80, "count": 10, "name": "New Article", "slug": "new-article"},
    {"id": 7, "count": 275, "name": "Newsletter", "slug": "newsletter"},
    {"id": 51, "count": 56, "name": "Notice", "slug": "notice"},
    {"id": 278, "count": 12, "name": "Offer", "slug": "offer"},
    {"id": 50, "count": 198, "name": "Onboarding", "slug": "onboarding"},
    {"id": 813, "count": 3, "name": "Opt-in", "slug": "opt-in"},
    {"id": 277, "count": 3, "name": "Order Shipped", "slug": "order-shipped"},
    {"id": 152, "count": 20, "name": "Password Reset", "slug": "password-reset"},
    {"id": 488, "count": 21, "name": "Personalized", "slug": "personalized"},
    {"id": 805, "count": 2, "name": "Price change", "slug": "price-change"},
    {"id": 208, "count": 49, "name": "Product Launch", "slug": "product-launch"},
    {"id": 74, "count": 116, "name": "Product Sale", "slug": "product-sale"},
    {"id": 69, "count": 194, "name": "Product Update", "slug": "product-update"},
    {"id": 104, "count": 235, "name": "Promotion", "slug": "promotion"},
    {"id": 315, "count": 105, "name": "Publication", "slug": "publication"},
    {"id": 150, "count": 69, "name": "Receipt", "slug": "receipt"},
    {"id": 259, "count": 12, "name": "Referral", "slug": "referral"},
    {"id": 361, "count": 3, "name": "Registration", "slug": "registration"},
    {"id": 223, "count": 38, "name": "Report", "slug": "report"},
    {"id": 532, "count": 2, "name": "Responsive", "slug": "responsive"},
    {"id": 40, "count": 225, "name": "Retention", "slug": "retention"},
    {"id": 214, "count": 9, "name": "Reviews", "slug": "reviews"},
    {"id": 849, "count": 1, "name": "Rsvp", "slug": "rsvp"},
    {"id": 552, "count": 18, "name": "Seasonal", "slug": "seasonal"},
    {"id": 171, "count": 2, "name": "Security", "slug": "security"},
    {"id": 197, "count": 4, "name": "Sharing", "slug": "sharing"},
    {"id": 237, "count": 8, "name": "Shipping", "slug": "shipping"},
    {"id": 584, "count": 1, "name": "Sign In", "slug": "sign-in"},
    {"id": 148, "count": 111, "name": "Social", "slug": "social"},
    {"id": 274, "count": 12, "name": "Subscription", "slug": "subscription"},
    {"id": 782, "count": 1, "name": "Summer", "slug": "summer"},
    {"id": 5, "count": 12, "name": "Support", "slug": "support"},
    {"id": 136, "count": 24, "name": "Survey", "slug": "survey"},
    {"id": 192, "count": 18, "name": "Text", "slug": "text"},
    {"id": 290, "count": 12, "name": "Thank You", "slug": "thank-you"},
    {"id": 38, "count": 164, "name": "Transactional", "slug": "transactional"},
    {"id": 281, "count": 7, "name": "Trial", "slug": "trial"},
    {"id": 1, "count": 0, "name": "Uncategorized", "slug": "uncategorized"},
    {"id": 269, "count": 2, "name": "Unsubscribe", "slug": "unsubscribe"},
    {"id": 202, "count": 12, "name": "Upselling", "slug": "upselling"},
    {"id": 439, "count": 13, "name": "Verification", "slug": "verification"},
    {"id": 31, "count": 10, "name": "Video", "slug": "post-format-video"},
    {"id": 781, "count": 3, "name": "Webinar", "slug": "webinar"},
    {"id": 2, "count": 175, "name": "Welcome", "slug": "welcome"},
    {"id": 810, "count": 3, "name": "Winback", "slug": "winback"}
  ]);
